### ISSUE TITLE
Compatibility with CKAN 2.9.7?

### ISSUE THREAD

**Issue by KatiRG** [mutantsan/ckanext-msal#2]
We tried this extension with CKAN 2.9.7 but could not make the login work: going to `/user/msal-login` did not trigger the Microsoft login process, but brought the user to the regular CKAN login screen with username and password.

For context, we are using a different [ckanext-msal repository](https://github.com/boykoc/ckanext-msal) which does not work with breaking changes introduced into CKAN 2.9.6. The specific problems are commented here: https://github.com/ckan/ckan/commit/b20423e617c285c83b4079bc859c751a274e7121?diff=split.

**Comment by kumarvivek1752** [comment]
@KatiRG  which version of CKAN is compatible with this extension?

**Comment by KatiRG** [comment]
@kumarvivek1752 I did not use this extension. We are using https://github.com/ongov/ckanext-msal which works for CKAN 2.9.6 and 2.9.7.

**Comment by mutantsan** [comment]
You can see the compatibility in the Readme. Currently, I have no plans to work on this extension, so you are free to fork it or create a PR.
